config/routes.rb
Rails.application.routes.draw do
  root :to =>'site#root'
  namespace :api, :defaults => {format: :json} do
  resources :instructions, only: [:index]
  resources :questions
  resources :answers
  resources :comments
  resources :upvotes
  resources :tags, only: [:create, :index ]

 end
resources :users
resource :session, only: [:new, :create, :destroy]
resources :instructions, only: [:index]

get 'auth/twitter/callback', to: 'sessions#create'

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :body, presence: true, uniqueness: true
  validates :user_id, presence: true
  has_many :comments
  has_many :answers
  has_many(
   :upvotes,
   :class_name => "Upvote",
   :foreign_key => :question_id,
   :primary_key => :id
  )

  has_many :tags
  belongs_to :user

  include PgSearch
  pg_search_scope :search, against: [:title, :body],
    using: {tsearch: {dictionary: "english"}},
    associated_against: {user: :name, comments: :body, tags: :category, answers: :body}

  def self.text_search(query)
      search(query)
  end

end

app/controllers/api/questions_controller.rb
class Api::QuestionsController < ApplicationController
  def new
    @question = Question.new
    render :new
  end

  def index
    if search?
    @questions = Question.text_search(params[:query])
    else
    @questions = Question.includes(:answers).all
    end
    render "index"
  end

  def show
    @question = Question.find(params[:id])
    @comments = @question.comments
    @answers = @question.answers
    render "show"
  end

  def create
   @question = Question.new(question_params)
   if params[:question][:response_notification] == "true"
     @question.response_notification= true;
   else
     @question.response_notification= false;
   end

   if signed_in?
     @question.user_id = current_user.id;
     if @question.save
       render json: @question
     else
     flash.now[:errors] = @question.errors.full_messages
     render :new
     end
   else
    flash.now[:errors] = "You have to be logged in to submit a question"
   end

  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :filepicker_url, :query)
  end

  def search?
    if params[:query]
      return true
    end
    false

  end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
    render :new
  end

  def index
    @questions = Question.all
    render :index
  end

  def show
    @question = Question.find(params[:id])
  end

  def create
   @question = Question.new(question_params)

   if params[:question][:response_notification] == "true"
     @question.response_notification= true;
   else
     @question.response_notification= false;
   end
   @question.user_id = current_user.id;

   if @question.try(:save)
     render :show
   else
   flash.now[:errors] = @question.errors.full_messages
   render :new
   end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def tag_params
    # use to add tags at some point
  end

end

app/views/questions/new.html.erb
<% if flash.now[:errors] %>
<% flash.now[:errors].each do |error| %>
<%=  error %>
   <% end %>
<% end %>

<form action=" <%= questions_url %>" method= "POST">
  <input type="hidden"
  name="authenticity_token"
  value=" <%= form_authenticity_token %>">
  <h1> Ask a Question </h1>
  <label for="question_title">Title </label>

  <input type="text" name="question[title]" id="question_title">

  <label for="question_body">Body </label>
  <textarea name="question[body]" id="question_body"></textarea>

  <label for="tags">Tags</label>
  <input type= "text" name="tag[tags]" id="question_tags">
  <input type="checkbox" name="question[response_notification]" value="true">
  notify me via email when there are new responses
  </input>
  <br>
  <button type="submit">Post Question</button>

</form>

app/views/questions/show.html.erb
<h1>Question:<h1>
<br>
<h1> <%= @question.title %> </h1>
<br>
<h2> <%= @question.body %> <h2>
<br>
<h1>Answer:<h1>
<br>
<p></p>
<h2> <% @question.answers.each do |answer| %>
     <%= answer.body %>
     <% end %>

<form action="<%=answers_url%>" method="post">
  <input type="hidden"
   name="authenticity_token"
   value="<%=form_authenticity_token%>">
   <input type="hidden"
    name="answer[question_id]"
    value="<%= @question.id %>">
  <label for="Answer">Answer</label>
   <textarea id="Answer"
   type="text"
   name="answer[body]">
 </textarea>
   <button class="answer">Post Answer</button>
<form>

  <p></p>
  <br>
  <form action="<%=comments_url%>" method="post">
    <input type="hidden"
     name="authenticity_token"
     value="<%=form_authenticity_token%>">
    <input type="hidden"
      name="comment[question_id]"
      value=" <%= @question.id %>">
    <label for="Comment">Comment</label>
     <textarea id="Comment"
     type="text"
     name="comment[body]">
   </textarea>
     <button class="comment">Post Comment</button>
  <form>