config/routes.rb
Rails.application.routes.draw do
  root :to =>'site#root'
  namespace :api, :defaults => {format: :json} do
  resources :instructions, only: [:index]
  resources :questions
  resources :answers
  resources :comments
  resources :upvotes
  resources :tags, only: [:create, :index ]

 end
resources :users
resource :session, only: [:new, :create, :destroy]
resources :instructions, only: [:index]

get 'auth/twitter/callback', to: 'sessions#create'

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def root

  end
end

app/views/site/root.html.erb
  <link href='https://fonts.googleapis.com/css?family=Amatic+SC:700,400' rel='stylesheet' type='text/css'>
<header class="navigation">
  <nav class="header-nav group">
  <a href="/#questions">  <h2 class="logo">Sea<em>Stack</em></h2></a>
      <ul class="navigation-tabs group">

      <% if !current_user %>
        <li>
          <form class="input" action="<%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="user[email]" value="guest.com">
            <input type="hidden" name="user[password]" value="password">
            <input type="hidden" name="user[url]" value="<%= request.fullpath %>">
            <input type="submit" value="guest login"></input>
          </form>

        </li>
        <li>
          <a href="/session/new">log in</a>
        </li>

        <% else %>
        <li>
          <form class="input" action="<%= "/session" %>" method="post">
            <input type="hidden" name="_method" value="delete">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="submit" value="Logout: <%= current_user.name %> "></input>
          </form>

        </li>

        <% end %>

        <li>
          <a href="/users/new">create account</a>
        </li>

        <!-- <li>help</li> -->

      </ul>
  </nav>
</header>


<!-- this is the navbar -->
<nav class="site-navigation group">

<a href="#questions">Questions</a>
<!-- <a href="">Tags</a> -->
<a href="#questions/new">Ask a Question</a>
<a href="#">Welcome Page</a>
</nav>
<!-- needed for html insert -->
<div class="">

</div>
<!-- load the backbone and javascript here so that it doesn't conflict with rails -->
<script>
  $(document).ready(function(){
    SeaStack.initialize()
  });
</script>